### ISSUE TITLE
Support for RedMine 5.0.5

### ISSUE THREAD

**Issue by ThomasBGithub** [two-pack/redmine_show_issue_assignee_avatar#2]
Hi,

is it possible to make this plugin compatible with redmine 5 ?

Best regards,

**Comment by two-pack** [comment]
In recent Redmine(after v3.4.0), the issue shows the avatar of the assignee without this plugin.
It has been implemented in this Issue.
https://www.redmine.org/issues/25775

Therefore, we believe that the role of this plugin is already over.

**Comment by ThomasBGithub** [comment]
Hi, thanks for your quick response.

The current behavior of Redmine is to show the avatar of the author as well as the avatar of the assignee. The avatar of the author is shown quite big, the one of the assignee is shown relatively small. 

We would like to only show the avatar of the assignee. Would you have an idea what’s the best way forward?

Thanks in advance.

**Comment by two-pack** [comment]
I think you can replace 
```plugins/redmine_show_issue_assignee_avatar/app/views/hooks/_view_issues_show_details_bottom.erb```
with the following code to do what you want to do.

```
<script type="text/javascript">
//<![CDATA[
$('div.gravatar-with-child > img.gravatar')[0].remove();
let srcset = $('div.gravatar-with-child > img.gravatar.gravatar-child').attr('srcset');
$('div.gravatar-with-child > img.gravatar.gravatar-child').attr({'srcset': srcset.replace(' 2x', '')});
//]]>
</script>
```

However, we are closing this Issue because we do not think it is something that should be addressed as this plugin.
Thanks for using the plugin and for issuing the issue.
